services:
  - type: web
    name: examnia-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    pythonVersion: 3.11
    envVars:
      - key: OPENAI_API_KEY
        sync: false
